[package]
name = "codotaku-engine-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
glam = "0.30.5"
vulkano = "0.35.2"
winit = { version = "0.30.12", features = ["rwh_06"] }
vulkano-shaders = "0.35.0"
bytemuck = "1.23.2"
lyon = "1.0.1"
